queue:
  server:
    host: "localhost"
    user: "iforge"
    password: "testpassword"
    database: "iforge print queue"
printers:
  working_folder: "iForge_Auto"
supervisor:
  update_interval: 30
web:
  port: 8000
  update_interval: 3600
  username: "iforge"
  password: "testingpassword"
email:
  address: "iforge@sheffield.ac.uk"
  name: "iForge"
  signature: "The iForge 3D Printing Team"