queue:
  server:
    host: "localhost"
    user: "SYSTEM_USERNAME"
    password: "SYSTEM_PASSWORD"
    database: "queue"
printers:
  working_folder: "auto_queue"
supervisor:
  update_interval: 30
web:
  port: 8000
  update_interval: 3600
  username: "YOUR_USERNAME"
  password: "YOUR_PASSWORD"
email:
  address: "Currently Unused"
  name: "Currently Unused"
  signature: "Currently Unused"
